services:
  factmatrix:
    build: .
    container_name: factmatrix-app
    expose:
      - "8501"           # 👈 internal only
    networks:
      - factmatrix-net
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: factmatrix-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - factmatrix-net
    restart: always

  grafana:
    image: grafana/grafana
    container_name: factmatrix-grafana
    networks:
      - factmatrix-net
    restart: always

networks:
  factmatrix-net:
    driver: bridge
